services:
  - type: web
    name: food-color-wheel-api
    env: python
    region: singapore
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    runtime: python-3.10
